---
engines:
  csslint:
    enabled: true
    checks:
      important:
        enabled: false
      regex-selectors:
        enabled: false
      bulletproof-font-face:
        enabled: false 
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  gofmt:
    enabled: true
  golint:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
  - "**.go"
exclude_paths: []
